### PR TITLE
unit conversion and scaling for Wh

### PR DESCRIPTION
**Pull request by louispt1**
Implemented unit switching for Joules to Watt Hours.

### Here is the UI element:
Screenshot 2024-08-02 at 12 27 58

### And this is an example of PJ to TWh:
Screenshot 2024-08-02 at 12 28 44

Screenshot 2024-08-02 at 12 29 15

### CODE REVIEW

**Comment by mabijkerk** [comment]
Looks really good! One last thought: when I download the CSV it is not explicit which unit it is in, but it seems to be set at PJ. Is it possible to 1) allow the download values to reflect the chart values and 2) add a unit column to the download?

**Comment by louispt1** [comment]
@mabijkerk Now the downloads reflect the chosen value - they are also scaled so they directly reflect the values shown in the chart / the table in the UI. The units are also in there in a separate column.

As for the spacing, I could fix the spacing for the table at the bottom so it stays in place, but couldn't find a way to fix the margin on the yAxis of the chart.

**Review by mabijkerk — APPROVED** [review]

**Review by kaskranenburgQ — COMMENTED** [review]
LGTM!

**Comment by kaskranenburgQ** [comment]
I just saw that the labels here on the left side are not rounded correctly. 

image

Here is the same graph in Wh:
image

Could you have a look @louispt1 ?

**Comment by louispt1** [comment]
I couldn't exactly replicate the scenario, but I think this latest commit should resolve the scaling issue. Please let me know if you encounter any similar situations @kaskranenburgQ !

**Review by noracato — APPROVED** [review]
Looks great! Works very well.

Nice work!

**Pull request merged**
